get bash to stop eating characters since \[ wasn't used
also add coloring to prompt based on return value
root prompt may no longer be #... haven't tested

diff --git a/agoraphobiae_rc b/agoraphobiae_rc
--- a/agoraphobiae_rc
+++ b/agoraphobiae_rc
@@ -33,17 +33,35 @@ GIT_PS1_SHOWCOLORHINTS=true
 GIT_PS1_SHOWUPSTREAM="auto"
 source ~/bin/git-prompt.sh
 # need to add the virtualenv thing back in
-function __venv_test () {
-	if test -z "$VIRTUAL_ENV" ; then
-		echo -n ""
+    PURPLE="\[\033[1;34m\]"
+    YELLOW="\[\033[1;33m\]"
+ LIGHT_RED="\[\033[1;31m\]"
+COLOR_NONE="\[\033[0m\]"
+# export PS1='\[\e[0;33m\]\u@\h:\W\[\e[0;33m\]$(__git_ps1 " (%s)") \$\[\e[m\] '
+function set_prompt_symbol () {
+	if test $1 -eq 0 ; then
+		PROMPT_SYMBOL="\$"
 	else
-		echo -ne "\033[1;34mvenv \033[0m"
+		PROMPT_SYMBOL="${LIGHT_RED}\$${COLOR_NONE}"
 	fi
 }
-# export PS1='\[\e[0;33m\]\u@\h:\W\[\e[0;33m\]$(__git_ps1 " (%s)") \$\[\e[m\] '
-AGORA_GIT_PROMPT_COMMAND='__git_ps1 "\[\e[0;33m\]\u@\h:\w\[\e[0m\]" "\[\e[0;33m\]\\\$\[\e[0m\] " ;'
-AGORA_VENV_PROMPT_COMMAND="__venv_test ;"
-export PROMPT_COMMAND="$AGORA_VENV_PROMPT_COMMAND $PROMPT_COMMAND $AGORA_GIT_PROMPT_COMMAND"
+function set_virtualenv () {
+	if test -z "$VIRTUAL_ENV" ; then
+		PYTHON_VIRTUALENV=""
+	else
+		PYTHON_VIRTUALENV="${PURPLE}venv ${COLOR_NONE}"
+	fi
+}
+function set_bash_prompt() {
+	# Set the PROMPT_SYMBOL variable. We do this first so we don't lose the
+	# return value of the last command.
+	set_prompt_symbol $?
+
+	set_virtualenv
+
+	BASH_PROMPT="${PYTHON_VIRTUALENV}${YELLOW}\u@\h:\w${COLOR_NONE}"
+}
+PROMPT_COMMAND='set_bash_prompt ; __git_ps1 "$BASH_PROMPT" "${YELLOW}${PROMPT_SYMBOL}${COLOR_NONE} "'
 
 # add ~/bin to the path
 # this ought to be in bashrc so noninteractive shells get this too
@@ -55,11 +73,12 @@ eval $(ssh-agent) &>/dev/null
 # git aliases
 alias gitpull='ssh-add && git pull'
 alias gitpullr='ssh-add && git pull --rebase'
-# tab completion for git
-source ~/bin/git-completion.bash
 
 if [[ "$(uname)" == CYGWIN* ]]; then
 	alias subl="/cygdrive/c/Program\ Files/Sublime\ Text\ 3/sublime_text.exe"
+else
+	# tab completion for git, which is already included in cygwin
+	source ~/bin/git-completion.bash
 fi
 # for vim
 stty -ixon
